import Head from "next/head";
import ArticleList from "../components/ArticleList";
import Introduction from "../components/Introduction";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Bottom from "../components/Bottom";
import { useState, useEffect } from "react";
import Donation from "../components/Donation";

var lang = "de";

export default function Home({ articles }) {
  console.log(articles);
  const [showDropDown, setShowDropDown] = useState(false);
  const [dis, setDisplay] = useState("block");
  const [lan, setLanguage] = useState("DE");

  useEffect(() => {
    if (showDropDown) {
      setDisplay("block");
    } else {
      setDisplay("none");
    }
  }, [showDropDown]);

  useEffect(() => {
    if (lan == "US") {
      lang = "us";
    } else {
      lang = "de";
    }
  }, [lan]);

  return (
    <div>
      <Head>
        <title>First page</title>
        <meta
          name="description"
          content="Generated by create next app, programming"
        />
      </Head>
      <div className={styles.dropdown_languages_box}>
        <div className={styles.dropdown_languages}>
          <p onClick={() => setShowDropDown(!showDropDown)}>{lan}</p>
          <div
            className={styles.dropdown_languages_inactive}
            style={{ display: dis }}
          >
            <ul>
              <li
                onClick={() => {
                  setShowDropDown(!showDropDown);
                  setLanguage("US");
                }}
              >
                EN
              </li>
              <li
                onClick={() => {
                  setShowDropDown(!showDropDown);
                  setLanguage("DE");
                }}
              >
                DE
              </li>
            </ul>
          </div>
        </div>
      </div>
      <Introduction />
      <div className={styles.home_box}>
        <div className={styles.home_box_text2}>
          <p>
            General, Business, Entertaiment, Health, Science, Sports, Technology
          </p>
          <h1>
            Different News <span>Categories</span>
          </h1>
          <p>
            Chose between them and read what you want or which suject is more
            interesting for you
          </p>
        </div>
        <div className={styles.cards}>
          {articles.articles.map((article) => (
            // eslint-disable-next-line react/jsx-key
            <div className={styles.card}>
              <img src={article.urlToImage} alt="" />
              <h2>{article.title}</h2>
              <h5 className={styles.date}>{article.publishedAt}</h5>
            </div>
          ))}
        </div>

        <div className={styles.home_box_text}>
          <p>
            General, Business, Entertaiment, Health, Science, Sports, Technology
          </p>
          <h1>
            Different News <span>Categories</span>
          </h1>
          <p>
            Chose between them and read what you want or which suject is more
            interesting for you
          </p>
        </div>
      </div>
      <Bottom />
      <Donation />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://newsapi.org/v2/top-headlines?country=${lang}&apiKey=YourApiKey`
  );
  const articles = await res.json();
  return {
    props: {
      articles,
    },
  };
};
